#!/usr/bin/env python
# vim: set softtabstop=2 ts=2 sw=2 expandtab: 
import urllib,urllib2


def send_post (username,oldpass,newpass,confirmpass):
  url = '#'
  values = {'action' : 'change',
          'confirmpassword' : confirmpass,
          'newpassword' : newpass,
          'oldpassword' : oldpass,
          'login' : username }
  postData = urllib.urlencode(values)
  print postData
  request = urllib2.Request(url,postData)
  response = urllib2.urlopen(request)
  print response.geturl()
  print response.info()
  thePage = response.read()
  print thePage


if __name__ == '__main__':
  send_post('cheese','noodle','pasta','buttons')
