#!/usr/bin/env ruby

refs = ARGF.read
repo_path = Dir.pwd
# This is a ruby based post-receive hook to e-mail footprints some shit, it's made to work with the existing Ruby post-receive hook from
# Git lab
# Call /opt/gitlab-post-receive-hook script
cmd = "/opt/gitlab-post-receive-hook #{repo_path} #{refs}"
puts `#{cmd}`
